dist: trusty
language: node_js
sudo: required
branches:
  only:
  - develop
  - /^release-.*/
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
node_js:
  - "10"
  - "9"
  - "8"
before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo apt-get install npm
install:
  - npm install
  - npm install -g mocha
before_script:
script:
  - mocha --timeout 120000 test/* --exit
after_script:
